title: Muhamad Agus Kurniawan # your name (or website title) here
logo: "/images/Foto_Fix.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br></br>
  Check My Profile here:
  <a href="https://github.com/agus2121"><img src="images/github.jpg?raw=true" width="100" height="100"></a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
