title: Muhamad Agus Kurniawan # your name (or website title) here
logo: "/images/Foto_Fix.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  Check my Profile here:
  <br></br>
  <a href="https://github.com/agus2121"><img src="images/github.png?raw=true" width="50" height="50"></a>
  <a href="https://www.linkedin.com/in/muhamad-agus-kurniawan-921900155/"><img src="images/linkedin1.png?raw=true" width="50" height="50"></a>
  <a href="https://public.tableau.com/app/profile/muhamad.agus.kurniawan"><img src="images/tableau1.png?raw=true" width="50" height="50"></a> 
  <a href="https://muhamadagus2120.medium.com/"><img src="images/medium1.png?raw=true" width="50" height="50"></a> 
  
  
theme: jekyll-theme-minimal
